{"name": "test_add_user_failed_check_existing", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_user_service.TestUserService object at 0x0000026351879950>\n\n    @pytest.mark.add_user_failed\n    def test_add_user_failed_check_existing(self):\n        try:\n            check_existing_user('Justin')\n>           assert False\nE           assert False\n\ntest\\test_user_service.py:93: AssertionError"}, "attachments": [{"name": "log", "source": "f99b0a9a-2526-48fe-9961-23a6117d0c20-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "578d9f71-6789-4771-95d8-b5c96aadcf4b-attachment.txt", "type": "text/plain"}], "start": 1703060046343, "stop": 1703060046344, "uuid": "89e719be-aa3b-46c2-bf04-89592d6e5969", "historyId": "c51ee9f992f6a20ee3ee36a693414b81", "testCaseId": "c51ee9f992f6a20ee3ee36a693414b81", "fullName": "test.test_user_service.TestUserService#test_add_user_failed_check_existing", "labels": [{"name": "tag", "value": "add_user_failed"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_user_service"}, {"name": "subSuite", "value": "TestUserService"}, {"name": "host", "value": "LAPTOP-SJL5AU2K"}, {"name": "thread", "value": "59520-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_user_service"}]}